baseURL = 'https://botlabs-gg.github.io/yagpdb-docs-v2'
languageCode = 'en-us'
title = 'YAGPDB Documentation v2'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
home = [ "HTML", "SEARCH" ]

[params]
themeVariant = [
    { identifier = "relearn-auto",  name = "Relearn Light/Dark", auto = [] },
	{ identifier = "relearn-light"  },
	{ identifier = "relearn-dark"   },
	{ identifier = "relearn-bright" },
	{ identifier = "zen-auto",      name = "Zen Light/Dark", auto = [ "zen-light", "zen-dark" ] },
	{ identifier = "zen-light"      },
	{ identifier = "zen-dark"       },
	{ identifier = "neon"           },
	{ identifier = "learn"          },
	{ identifier = "blue"           },
	{ identifier = "green"          },
	{ identifier = "red"            }
]

collapsibleMenu = true
disableRootBreadcrumb = true
