# To avoid weirdness with images and whatnot, this is empty and instead set at build time.
# See also https://discourse.gohugo.io/t/solved-what-should-be-used-for-the-value-of-site-baseurl/5896
baseURL = ''
languageCode = 'en-us'
title = 'YAGPDB Documentation v2'

uglyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enable HTML tags in Markdown
      unsafe = true

[module]
  [[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
  home = [ "HTML", "SEARCH" ]

[params]
  themeVariant = [
  { identifier = "relearn-auto",  name = "Relearn Light/Dark", auto = [] },
  { identifier = "relearn-light"  },
  { identifier = "relearn-dark"   },
  { identifier = "relearn-bright" },
  { identifier = "zen-auto",      name = "Zen Light/Dark", auto = [ "zen-light", "zen-dark" ] },
  { identifier = "zen-light"      },
  { identifier = "zen-dark"       },
  { identifier = "neon"           },
  { identifier = "learn"          },
  { identifier = "blue"           },
  { identifier = "green"          },
  { identifier = "red"            }
  ]

  collapsibleMenu = true
  disableRootBreadcrumb = true
  disableInlineCopyToClipboard = true
  editURL = 'https://github.com/botlabs-gg/yagpdb-docs-v2/edit/master/content/'
